# This is an example configuration file to go with the example
# complete_simulation.py

name: 'Gridsim example simulation'

start_trial: 1
end_trial: 10

grid_width: 50  # 50 x 50 grid
environment_img: 'ex_env.png'

num_steps: 100  # Number of steps per trial
num_robots: 20

# Initial robot positions
init_x_pos: [5, 20, 30]
init_y_pos: [5, 20, 40]

# Communication radius
# comm_range: 3

# Don't overwrite existing data
# (Will exit instead of overwriting)
overwrite_trials: true
log_filename: 'test.h5'
